### ISSUE TITLE
Check if TankDriver works on integrated video adapter

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/TankDriver#23]
It may fail on Windows without proper video adapter, need to check.

**Comment by ForNeVeR** [comment]
No it doesn't. Here's the exception:

```
Unhandled Exception: System.PlatformNotSupportedException: MonoGame requires either ARB_framebuffer_object or EXT_framebuffer_object.Try updating your graphics drivers.
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformInitialize()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Initialize()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Initialize()
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.GamePlatform.BeforeInitialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at TankDriver.App.Program.Main(String[] args) in C:\Projects\TankDriver\TankDriver.App\Program.cs:line 29
```
